name : anime quotes


on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          go version
        
       - name: Running
        timeout-minutes: 350
        continue-on-error: true
          run: |
            go run main.go
