name : anime quotes


on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: setup go
        uses: actions/setup-go@v2
        with:
         go-version: "1.14.0"
      
      - name: Install dependencies
        run: |
          go version
        
      - name: Running
        timeout-minutes: 350
        continue-on-error: true
        run: |
          go run quote.go
