name : discord bot


on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        

      - name: Run build
      run: go build . 
      
      - name: Run vet & lint
      run: |
        go vet .
        golint .

       - name: Running
         timeout-minutes: 350
         continue-on-error: true
         run: |
           go run main.go
